[login.dev]
id = "" # TO BE FILLED
password = "" # TO BE FILLED

[login.account]
id = "" # TO BE FILLED
password = "" # TO BE FILLED

[images.dimensions]
screenDims = [640, 480]
barsSizes = [42, 42]
padding = [12, 12]

[images.filters]
brightness = 1
blurLevel = 0
withCartridge = true
mask = "Bars"

[scan]
hintFile = "hint.toml"
ignoredFormat = [".png", ".txt", ".png", ".sav"]
language = "en"
regions = ["eu", "us", "wor", "jp", "ss"]