[[console]]
generic = "Doom"
id = 290
format = [".doom"]
width = 224
hint = "doom"
procedure = "doom"

[[console]]
generic = "Nintendo Game Boy"
id = 9
format = [".gb"]
hint = "gb"
width = 224

[[console]]
generic = "Nintendo Game Boy Advance"
id = 12
format = [".gba"]
hint = "gba"
width = 256

[[console]]
generic = "Nintendo Game Boy Color"
id = 10
format = [".gbc"]
hint = "gbc"
width = 224

[[console]]
generic = "Nintendo NES-Famicom"
id = 3
format = [".nes"]
hint = "nes"
width = 224

[[console]]
generic = "Nintendo SNES-SFC"
id = 4
format = [".sfc"]
hint = "snes"
width = 256

[[console]]
generic = "PICO-8"
id = 234
format = [".p8"]
hint = "pico"
width = 224

[[console]]
generic = "Sega 32X"
id = 19
format = [".32x"]
hint = "32x"
width = 256

[[console]]
generic = "Sega Master System"
id = 2
format = [".sms"]
hint = "sms"
width = 256

[[console]]
generic = "Sega Mega CD - Sega CD"
id = 20
format = [".chd", ".iso"]
hint = "segacd"
width = 224

[[console]]
generic = "Sega Mega Drive - Genesis"
id = 1
format = [".md"]
hint = "megadrive"
width = 256

[[console]]
generic = "External - Ports"
id = 138
format = [".sh"]
hint = "pm"
width = 224

[[console]]
generic = "Sega Saturn"
id = 22
format = [".chd"]
hint = "sega_s"
width = 224

# More consoles can be added later on, be ready to use hints though